apiVersion: v1
kind: ConfigMap
metadata:
  name: reactive-web-service
  labels:
    app: reactive-web-service
data:
  perkss.kafka.example.bootstrap-servers: kafka-2
  perkss.kafka.example.input-topic: social-media-posts
  perkss.kafka.example.consumer-group-id: websocket-topology